#!/usr/bin/env python3
"""Compose the packaged native stub from an explicit ordered fragment list."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
FRAGMENTS = (
    PACKAGE_ROOT / "stubs" / "_native" / "manual.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "generated.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "dictionary.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "domain_enums.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "source.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "diagnostics.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "dialect.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "morphology.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "jvozba.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "syntax.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "parser.pyi",
)
OUTPUT = PACKAGE_ROOT / "python" / "jbotci" / "_native.pyi"
HEADER = "# Generated by tools/compose_stubs.py; do not edit directly.\n"


def compose() -> str:
    """Return the canonical native stub text."""
    fragments = tuple(path.read_text(encoding="utf-8").strip() for path in FRAGMENTS)
    return HEADER + "\n\n".join(fragments) + "\n"


def parse_args() -> argparse.Namespace:
    """Parse compositor command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the packaged stub is stale",
    )
    return parser.parse_args()


def main() -> int:
    """Write or validate the deterministic composition result."""
    args = parse_args()
    expected = compose()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") == expected:
            return 0
        print(f"{OUTPUT} is stale; run {Path(__file__).name}", file=sys.stderr)
        return 1
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
