#!/usr/bin/env python3
"""Compose the packaged native stub from an explicit ordered fragment list."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
WORKSPACE_ROOT = PACKAGE_ROOT.parents[1]
FRAGMENTS = (
    PACKAGE_ROOT / "stubs" / "_native" / "manual.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "generated.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "dictionary.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "domain_enums.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "source.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "diagnostics.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "dialect.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "morphology.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "jvozba.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "syntax.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "parser.pyi",
    PACKAGE_ROOT / "stubs" / "_native" / "references.pyi",
)
OUTPUT = PACKAGE_ROOT / "python" / "jbotci" / "_native.pyi"
HEADER = "# Generated by tools/compose_stubs.py; do not edit directly.\n"
RUST_DOC_MARKER = re.compile(r'"""@rust-doc:([A-Za-z_][A-Za-z0-9_]*)"""')
PARSER_SOURCE = PACKAGE_ROOT / "src" / "parser.rs"


def rust_pyclass_docs() -> dict[str, str]:
    """Extract public class documentation from the Rust declarations."""
    result = subprocess.run(
        [
            "cargo",
            "run",
            "--quiet",
            "-p",
            "jbotci-python-api-parity",
            "--",
            "pyclass-docs",
            str(PARSER_SOURCE.relative_to(WORKSPACE_ROOT)),
        ],
        cwd=WORKSPACE_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr or result.stdout)
    docs: dict[str, str] = {}
    for line in result.stdout.splitlines():
        name, encoded = line.split("\t", 1)
        docs[name] = bytes.fromhex(encoded).decode("utf-8")
    return docs


def insert_rust_docstrings(source: str) -> str:
    """Replace native-stub markers with docs from their Rust declarations."""
    docs = rust_pyclass_docs()
    markers = set(RUST_DOC_MARKER.findall(source))
    missing = markers - docs.keys()
    if missing:
        raise RuntimeError(
            "Rust parser declarations have no docs for: "
            + ", ".join(sorted(missing))
        )
    return RUST_DOC_MARKER.sub(lambda match: repr(docs[match.group(1)]), source)


def compose() -> str:
    """Return the canonical native stub text."""
    fragments = tuple(path.read_text(encoding="utf-8").strip() for path in FRAGMENTS)
    return insert_rust_docstrings(HEADER + "\n\n".join(fragments) + "\n")


def parse_args() -> argparse.Namespace:
    """Parse compositor command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the packaged stub is stale",
    )
    return parser.parse_args()


def main() -> int:
    """Write or validate the deterministic composition result."""
    args = parse_args()
    expected = compose()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") == expected:
            return 0
        print(f"{OUTPUT} is stale; run {Path(__file__).name}", file=sys.stderr)
        return 1
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
