#!/usr/bin/env python3
"""Generate exact native StrEnum stubs from the Rust domain metadata sources."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = PACKAGE_ROOT.parents[1]
OUTPUT = PACKAGE_ROOT / "stubs" / "_native" / "domain_enums.pyi"
HEADER = """# Generated by tools/generate_domain_enum_stubs.py; do not edit directly.
from enum import StrEnum
from typing import final

"""


def braced_body(source: str, start: int) -> str:
    """Return the contents of the brace that starts at or after ``start``."""

    opening = source.index("{", start)
    depth = 0
    for index in range(opening, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[opening + 1 : index]
    raise ValueError("unterminated Rust brace block")


def impl_function_pairs(source: str, type_name: str, function_name: str) -> list[tuple[str, str]]:
    """Extract ``Self::Variant => \"value\"`` pairs from one inherent method."""

    impl_start = source.index(f"impl {type_name} {{")
    impl_body = braced_body(source, impl_start)
    function_start = impl_body.index(f"fn {function_name}")
    function_body = braced_body(impl_body, function_start)
    return re.findall(r'Self::(\w+)\s*=>\s*"([^"]+)"', function_body)


def metadata_enums(sources: list[str]) -> list[tuple[str, list[tuple[str, str]]]]:
    """Extract member/value pairs from single-source Rust enum declarations."""

    values: list[tuple[str, list[tuple[str, str]]]] = []
    invocation = re.compile(r"(?:crate::)?define_string_enum_metadata!\s*\{")
    for source in sources:
        for match in invocation.finditer(source):
            body = braced_body(source, match.start())
            type_match = re.search(r"pub enum (\w+)\s*\{", body)
            if type_match is None:
                raise ValueError("string-enum declaration has no public enum")
            enum_body = braced_body(body, type_match.start())
            pairs = re.findall(
                r'\w+\s*=>\s*\("([^"]+)",\s*"([^"]+)"\)', enum_body
            )
            if not pairs:
                raise ValueError(f"no metadata entries found for {type_match.group(1)}")
            values.append((type_match.group(1), pairs))
    return values


def declared_string_enum(
    source: str, type_name: str
) -> tuple[str, list[tuple[str, str]]]:
    """Read pairs from a ``define_string_enum!`` single-source declaration."""

    declaration = source.index(f"pub enum {type_name} {{")
    body = braced_body(source, declaration)
    values = re.findall(r'\w+\s*=>\s*"([^"]+)"', body)
    if not values:
        raise ValueError(f"no string-enum declaration entries found for {type_name}")
    return type_name, [(value.replace("-", "_").upper(), value) for value in values]


def cmavo_pairs(source: str) -> list[tuple[str, str]]:
    """Extract Python member/canonical spelling pairs from the single cmavo table."""

    table = source[
        source.index("macro_rules! cmavo_table") : source.index("macro_rules! declare_cmavo_enum")
    ]
    return [
        (variant.upper(), spelling)
        for variant, spelling in re.findall(
            r'^\s*(\w+)\s*=>\s*\{\s*text:\s*"([^"]+)"', table, re.MULTILINE
        )
    ]


def inherent_enum(
    source: str,
    type_name: str,
    member_function: str,
    value_function: str,
) -> tuple[str, list[tuple[str, str]]]:
    """Join member and value methods by their Rust variant identifier."""

    members = dict(impl_function_pairs(source, type_name, member_function))
    values = dict(impl_function_pairs(source, type_name, value_function))
    if members.keys() != values.keys():
        raise ValueError(f"metadata methods disagree for {type_name}")
    return type_name, [(members[variant], values[variant]) for variant in members]


def render_enum(native_prefix: str, type_name: str, pairs: list[tuple[str, str]]) -> str:
    """Render one private native enum class after uniqueness validation."""

    if not pairs:
        raise ValueError(f"{type_name} has no variants")
    names = [name for name, _ in pairs]
    values = [value for _, value in pairs]
    if len(names) != len(set(names)):
        raise ValueError(f"duplicate Python member name in {type_name}")
    if len(values) != len(set(values)):
        raise ValueError(f"duplicate canonical value in {type_name}")
    lines = ["@final", f"class _{native_prefix}_{type_name}(StrEnum):"]
    lines.extend(f"    {name} = {value!r}" for name, value in pairs)
    return "\n".join(lines)


def generate() -> str:
    """Return the complete deterministic enum fragment."""

    diagnostics = (REPOSITORY_ROOT / "crates/jbotci-diagnostics/src/lib.rs").read_text()
    dialect = (REPOSITORY_ROOT / "crates/jbotci-dialect/src/lib.rs").read_text()
    morphology_root = REPOSITORY_ROOT / "crates/jbotci-morphology/src"
    morphology = (morphology_root / "lib.rs").read_text()
    morphology_metadata_sources = [
        morphology,
        (morphology_root / "lujvo.rs").read_text(),
        (morphology_root / "segment/phonotactics.rs").read_text(),
        (morphology_root / "surface.rs").read_text(),
    ]
    cmavo = (REPOSITORY_ROOT / "crates/jbotci-morphology/src/cmavo.rs").read_text()

    enums: list[tuple[str, str, list[tuple[str, str]]]] = []
    for type_name in (
        "DiagnosticSeverity",
        "DiagnosticPhase",
        "TracePhase",
        "TraceLevel",
        "TraceEventKind",
        "DiagnosticDetailMode",
        "DiagnosticNoteMode",
        "DiagnosticTextRole",
    ):
        _, pairs = declared_string_enum(diagnostics, type_name)
        enums.append(("diagnostics", type_name, pairs))
    dialect_values = impl_function_pairs(dialect, "DialectFeature", "name")
    enums.append(
        (
            "dialect",
            "DialectFeature",
            [(value.replace("-", "_").upper(), value) for _, value in dialect_values],
        )
    )
    enums.extend(
        ("morphology", type_name, pairs)
        for type_name, pairs in metadata_enums(morphology_metadata_sources)
    )
    enums.append(("morphology", "Cmavo", cmavo_pairs(cmavo)))
    selmaho_values = impl_function_pairs(cmavo, "Selmaho", "name")
    enums.append(
        ("morphology", "Selmaho", [(value.upper(), value) for _, value in selmaho_values])
    )

    return HEADER + "\n\n".join(
        render_enum(prefix, type_name, pairs) for prefix, type_name, pairs in enums
    ) + "\n"


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    """Write or validate the generated fragment."""

    expected = generate()
    if parse_args().check:
        if OUTPUT.read_text(encoding="utf-8") == expected:
            return 0
        print(f"{OUTPUT} is stale; run {Path(__file__).name}", file=sys.stderr)
        return 1
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
