#!/usr/bin/env python3
"""Generate exact native StrEnum stubs from the Rust domain metadata sources."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = PACKAGE_ROOT.parents[1]
OUTPUT = PACKAGE_ROOT / "stubs" / "_native" / "domain_enums.pyi"
HEADER = """# Generated by tools/generate_domain_enum_stubs.py; do not edit directly.
from enum import StrEnum
from typing import final

"""

ENUM_METHODS: dict[tuple[str, str], tuple[str, ...]] = {
    ("diagnostics", "TracePhase"): (
        "    def includes(self, phase: _diagnostics_TracePhase) -> bool: ...",
    ),
    ("diagnostics", "TraceLevel"): (
        "    def number(self) -> int: ...",
        "    @staticmethod",
        "    def from_number(value: int) -> _diagnostics_TraceLevel: ...",
    ),
    ("diagnostics", "DiagnosticNoteMode"): (
        "    def visible_in(self, detail: _diagnostics_DiagnosticDetailMode) -> bool: ...",
    ),
    ("dialect", "DialectFeature"): (
        "    def atom_name(self) -> str: ...",
    ),
}


def braced_body(source: str, start: int) -> str:
    """Return the contents of the brace that starts at or after ``start``."""

    opening = source.index("{", start)
    depth = 0
    for index in range(opening, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[opening + 1 : index]
    raise ValueError("unterminated Rust brace block")


def metadata_enums(sources: list[str]) -> list[tuple[str, list[tuple[str, str]]]]:
    """Extract member/value pairs from single-source Rust enum declarations."""

    values: list[tuple[str, list[tuple[str, str]]]] = []
    invocation = re.compile(r"(?:crate::)?define_string_enum_metadata!\s*\{")
    for source in sources:
        for match in invocation.finditer(source):
            body = braced_body(source, match.start())
            type_match = re.search(r"pub enum (\w+)\s*\{", body)
            if type_match is None:
                raise ValueError("string-enum declaration has no public enum")
            enum_body = braced_body(body, type_match.start())
            declared_variants = re.findall(r"^\s*(\w+)\s*=>", enum_body, re.MULTILINE)
            entries = re.findall(
                r'^\s*(\w+)\s*=>\s*\("([^"]+)",\s*"([^"]+)"\)',
                enum_body,
                re.MULTILINE,
            )
            if declared_variants != [variant for variant, _, _ in entries]:
                raise ValueError(
                    f"metadata extraction omitted a variant of {type_match.group(1)}"
                )
            pairs = [(member, value) for _, member, value in entries]
            if not pairs:
                raise ValueError(f"no metadata entries found for {type_match.group(1)}")
            values.append((type_match.group(1), pairs))
    return values


def declared_string_enums(source: str) -> list[tuple[str, list[tuple[str, str]]]]:
    """Read every ``define_string_enum!`` single-source declaration."""

    values: list[tuple[str, list[tuple[str, str]]]] = []
    invocation = re.compile(r"(?:crate::)?define_string_enum!\s*\{")
    for match in invocation.finditer(source):
        declaration = braced_body(source, match.start())
        type_match = re.search(r"pub enum (\w+)\s*\{", declaration)
        if type_match is None:
            raise ValueError("string-enum declaration has no public enum")
        body = braced_body(declaration, type_match.start())
        declared_variants = re.findall(r"^\s*(\w+)\s*=>", body, re.MULTILINE)
        entries = re.findall(r'^\s*(\w+)\s*=>\s*"([^"]+)"', body, re.MULTILINE)
        type_name = type_match.group(1)
        if declared_variants != [variant for variant, _ in entries]:
            raise ValueError(f"string-enum extraction omitted a variant of {type_name}")
        if not entries:
            raise ValueError(f"no string-enum declaration entries found for {type_name}")
        values.append(
            (
                type_name,
                [
                    (value.replace("-", "_").upper(), value)
                    for _, value in entries
                ],
            )
        )
    return values


def syntax_binding_enums(source: str) -> list[tuple[str, list[tuple[str, str]]]]:
    """Read exhaustive syntax binding enum declarations from their one macro source."""

    values: list[tuple[str, list[tuple[str, str]]]] = []
    invocation = re.compile(
        r'define_syntax_string_enum_binding!\s*\(\s*[\w:]+\s*,\s*"[^"]+"\s*,\s*"([^"]+)"\s*,\s*\{'
    )
    for match in invocation.finditer(source):
        type_name = match.group(1)
        body = braced_body(source, match.end() - 1)
        entries = re.findall(
            r'^\s*[\w:]+::\w+\s*=>\s*\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)',
            body,
            re.MULTILINE,
        )
        declared = re.findall(r"^\s*[\w:]+::\w+\s*=>", body, re.MULTILINE)
        if len(declared) != len(entries):
            raise ValueError(f"syntax enum extraction omitted a variant of {type_name}")
        if not entries:
            raise ValueError(f"no syntax enum entries found for {type_name}")
        values.append((type_name, entries))
    return values


def cmavo_pairs(source: str) -> list[tuple[str, str]]:
    """Extract Python member/canonical spelling pairs from the single cmavo table."""

    table = source[
        source.index("macro_rules! cmavo_table") : source.index("macro_rules! declare_cmavo_enum")
    ]
    declared_variants = re.findall(r"^\s*(\w+)\s*=>", table, re.MULTILINE)
    entries = re.findall(
        r'^\s*(\w+)\s*=>\s*\{\s*text:\s*"([^"]+)"', table, re.MULTILINE
    )
    if declared_variants != [variant for variant, _ in entries]:
        raise ValueError("cmavo metadata extraction omitted a table entry")
    return [(variant.upper(), spelling) for variant, spelling in entries]


def dialect_feature_pairs(source: str) -> list[tuple[str, str]]:
    """Extract Python members from the single declarative dialect-feature table."""

    start = source.index("define_dialect_features! {")
    body = braced_body(source, start)
    declared_variants = re.findall(r"^\s*(\w+)\s*=>", body, re.MULTILINE)
    entries = re.findall(
        r'^\s*(\w+)\s*=>\s*"([^"]+)"', body, re.MULTILINE
    )
    if declared_variants != [variant for variant, _ in entries]:
        raise ValueError("dialect feature metadata extraction omitted a table entry")
    return [
        (value.replace("-", "_").upper(), value) for _, value in entries
    ]


def selmaho_pairs(source: str) -> list[tuple[str, str]]:
    """Extract Python members from the single selma'o metadata table."""

    start = source.index("define_selmaho! {")
    body = braced_body(source, start)
    declared_variants = re.findall(r"^\s*(\w+)\s*=>", body, re.MULTILINE)
    entries = re.findall(r'^\s*(\w+)\s*=>\s*"([^"]+)"', body, re.MULTILINE)
    if declared_variants != [variant for variant, _ in entries]:
        raise ValueError("selma'o metadata extraction omitted a table entry")
    return [(value.upper(), value) for _, value in entries]


def render_enum(native_prefix: str, type_name: str, pairs: list[tuple[str, str]]) -> str:
    """Render one private native enum class after uniqueness validation."""

    if not pairs:
        raise ValueError(f"{type_name} has no variants")
    names = [name for name, _ in pairs]
    values = [value for _, value in pairs]
    if len(names) != len(set(names)):
        raise ValueError(f"duplicate Python member name in {type_name}")
    if len(values) != len(set(values)):
        raise ValueError(f"duplicate canonical value in {type_name}")
    lines = ["@final", f"class _{native_prefix}_{type_name}(StrEnum):"]
    lines.extend(f"    {name} = {value!r}" for name, value in pairs)
    lines.extend(ENUM_METHODS.get((native_prefix, type_name), ()))
    return "\n".join(lines)


def generate() -> str:
    """Return the complete deterministic enum fragment."""

    diagnostics = (REPOSITORY_ROOT / "crates/jbotci-diagnostics/src/lib.rs").read_text()
    dialect = (REPOSITORY_ROOT / "crates/jbotci-dialect/src/lib.rs").read_text()
    morphology_root = REPOSITORY_ROOT / "crates/jbotci-morphology/src"
    morphology_metadata_sources = [
        path.read_text() for path in sorted(morphology_root.rglob("*.rs"))
    ]
    cmavo = (REPOSITORY_ROOT / "crates/jbotci-morphology/src/cmavo.rs").read_text()
    syntax_parser = (PACKAGE_ROOT / "src/parser.rs").read_text()

    enums: list[tuple[str, str, list[tuple[str, str]]]] = []
    enums.extend(
        ("diagnostics", type_name, pairs)
        for type_name, pairs in declared_string_enums(diagnostics)
    )
    enums.append(
        (
            "dialect",
            "DialectFeature",
            dialect_feature_pairs(dialect),
        )
    )
    enums.extend(
        ("morphology", type_name, pairs)
        for type_name, pairs in metadata_enums(morphology_metadata_sources)
    )
    enums.append(("morphology", "Cmavo", cmavo_pairs(cmavo)))
    enums.append(("morphology", "Selmaho", selmaho_pairs(cmavo)))
    enums.extend(
        ("syntax_parser", type_name, pairs)
        for type_name, pairs in syntax_binding_enums(syntax_parser)
    )

    return HEADER + "\n\n".join(
        render_enum(prefix, type_name, pairs) for prefix, type_name, pairs in enums
    ) + "\n"


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    """Write or validate the generated fragment."""

    expected = generate()
    if parse_args().check:
        if OUTPUT.read_text(encoding="utf-8") == expected:
            return 0
        print(f"{OUTPUT} is stale; run {Path(__file__).name}", file=sys.stderr)
        return 1
    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
