[application]
name = "jbotci"
default_platform = "web"
asset_dir = "../../crates/jbotci-ui/assets"
public_dir = "../../target/jbotci-web-public"
out_dir = "../../dist"

[bundle]
identifier = "org.int19h.jbotci"
publisher = "int19h"
category = "Reference"
short_description = "Lojban tool"
icon = [
    "../../crates/jbotci-ui/assets/icons/jbotci-icon.icns",
    "../../crates/jbotci-ui/assets/icons/jbotci-icon-512.png",
]

[bundle.macos]
bundle_name = "jbotci"

[bundle.deb]
desktop_template = "apps/jbotci-app/bundle/linux/jbotci.desktop.hbs"

[bundle.windows.wix]
template = "bundle/windows/jbotci.wxs.hbs"
upgrade_code = "5fc2c34f-0231-53b4-af97-bd710d8abad2"

[web.app]
title = "jbotci"

[web.watcher]
reload_html = true
watch_path = ["src", "../../crates/jbotci-ui/src", "../../crates/jbotci-ui/assets", "index.html"]
