changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - A-ci
        - A-tooling
        - contracts
        - refactor
        - testing
    - title: Other changes
      labels:
        - "*"
