[package]
name = "jbotci-syntax-macros"
description = "Proc-macro implementation for jbotci syntax grammar declarations."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
bityzba.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[build-dependencies]
bityzba = { workspace = true, features = ["contract_scanner"] }

[dev-dependencies]
bityzba.workspace = true
jbotci-source.workspace = true
jbotci-tree.workspace = true
serde.workspace = true
smallvec.workspace = true
trybuild = "1"
vec1.workspace = true

[lints]
workspace = true
