[application]
name = "jbotci-web"
default_platform = "web"
asset_dir = "../../crates/jbotci-ui/assets"
public_dir = "../../target/jbotci-web-public"
out_dir = "dist"

[web.app]
title = "jbotci"

[web.watcher]
reload_html = true
watch_path = ["src", "../../crates/jbotci-ui/src", "../../crates/jbotci-ui/assets", "index.html"]
