from collections.abc import Sequence
from typing import Final, final

_diagnostics_DEFAULT_TRACE_LIMIT: Final[int]

@final
class _diagnostics_InvalidTraceLevel:
    __match_args__: tuple[str]
    def __new__(cls, value: int) -> _diagnostics_InvalidTraceLevel: ...
    @property
    def value(self) -> int: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

@final
class _diagnostics_TraceFilter:
    def __new__(cls, name: str) -> _diagnostics_TraceFilter: ...
    @property
    def name(self) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

@final
class _diagnostics_TraceOptions:
    def __new__(
        cls,
        *,
        enabled: bool = ...,
        level: _diagnostics_TraceLevel | None = ...,
        filter: _diagnostics_TraceFilter | None = ...,
        phase: _diagnostics_TracePhase | None = ...,
        limit: int = ...,
    ) -> _diagnostics_TraceOptions: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def level(self) -> _diagnostics_TraceLevel: ...
    @property
    def filter(self) -> _diagnostics_TraceFilter | None: ...
    @property
    def phase(self) -> _diagnostics_TracePhase: ...
    @property
    def limit(self) -> int: ...
    def with_phase(self, /, phase: _diagnostics_TracePhase) -> _diagnostics_TraceOptions: ...
    def with_limit(self, /, limit: int) -> _diagnostics_TraceOptions: ...
    def includes(self, /, phase: _diagnostics_TracePhase) -> bool: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_TraceEvent:
    def __new__(
        cls,
        phase: _diagnostics_TracePhase,
        level: _diagnostics_TraceLevel,
        depth: int,
        kind: _diagnostics_TraceEventKind,
        label: str,
        byte_start: int,
        byte_end: int,
        detail: str | None = ...,
    ) -> _diagnostics_TraceEvent: ...
    @property
    def phase(self) -> _diagnostics_TracePhase: ...
    @property
    def level(self) -> _diagnostics_TraceLevel: ...
    @property
    def depth(self) -> int: ...
    @property
    def kind(self) -> _diagnostics_TraceEventKind: ...
    @property
    def label(self) -> str: ...
    @property
    def byte_start(self) -> int: ...
    @property
    def byte_end(self) -> int: ...
    @property
    def detail(self) -> str | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_TraceContext:
    def __new__(cls, construct: str, byte_start: int, byte_end: int) -> _diagnostics_TraceContext: ...
    @property
    def construct(self) -> str: ...
    @property
    def byte_start(self) -> int: ...
    @property
    def byte_end(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_TraceFailureBranch:
    def __new__(
        cls,
        contexts: Sequence[_diagnostics_TraceContext] = ...,
        expected: Sequence[str] = ...,
    ) -> _diagnostics_TraceFailureBranch: ...
    @property
    def contexts(self) -> tuple[_diagnostics_TraceContext, ...]: ...
    @property
    def expected(self) -> tuple[str, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_TraceFailureSummary:
    def __new__(
        cls,
        byte_start: int,
        byte_end: int,
        reason: str,
        branches: Sequence[_diagnostics_TraceFailureBranch] = ...,
        current_context: _diagnostics_TraceContext | None = ...,
    ) -> _diagnostics_TraceFailureSummary: ...
    @property
    def byte_start(self) -> int: ...
    @property
    def byte_end(self) -> int: ...
    @property
    def reason(self) -> str: ...
    @property
    def branches(self) -> tuple[_diagnostics_TraceFailureBranch, ...]: ...
    @property
    def current_context(self) -> _diagnostics_TraceContext | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_TraceReport:
    def __new__(
        cls,
        phase: _diagnostics_TracePhase,
        events: Sequence[_diagnostics_TraceEvent] = ...,
        *,
        truncated: bool = ...,
        failure: _diagnostics_TraceFailureSummary | None = ...,
    ) -> _diagnostics_TraceReport: ...
    @property
    def phase(self) -> _diagnostics_TracePhase: ...
    @property
    def events(self) -> tuple[_diagnostics_TraceEvent, ...]: ...
    @property
    def truncated(self) -> bool: ...
    @property
    def failure(self) -> _diagnostics_TraceFailureSummary | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_VlackuWordLink:
    __match_args__: tuple[str]
    def __new__(cls, word: str) -> _diagnostics_VlackuWordLink: ...
    @property
    def word(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_CllSectionLink:
    __match_args__: tuple[str, str]
    def __new__(cls, section_id: str, anchor: str | None = ...) -> _diagnostics_CllSectionLink: ...
    @property
    def section_id(self) -> str: ...
    @property
    def anchor(self) -> str | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_EbnfRuleLink:
    __match_args__: tuple[str]
    def __new__(cls, rule_name: str) -> _diagnostics_EbnfRuleLink: ...
    @property
    def rule_name(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_DiagnosticTextSegment:
    def __new__(
        cls,
        role: _diagnostics_DiagnosticTextRole,
        text: str,
        *,
        link: _diagnostics_VlackuWordLink | _diagnostics_CllSectionLink | _diagnostics_EbnfRuleLink | None = ...,
    ) -> _diagnostics_DiagnosticTextSegment: ...
    @property
    def role(self) -> _diagnostics_DiagnosticTextRole: ...
    @property
    def text(self) -> str: ...
    @property
    def link(self) -> _diagnostics_VlackuWordLink | _diagnostics_CllSectionLink | _diagnostics_EbnfRuleLink | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_DiagnosticStyledNote:
    def __new__(
        cls,
        mode: _diagnostics_DiagnosticNoteMode,
        segments: Sequence[_diagnostics_DiagnosticTextSegment],
    ) -> _diagnostics_DiagnosticStyledNote: ...
    @property
    def mode(self) -> _diagnostics_DiagnosticNoteMode: ...
    @property
    def segments(self) -> tuple[_diagnostics_DiagnosticTextSegment, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_DiagnosticLabel:
    def __new__(
        cls,
        span: _source_SourceSpan,
        message: str,
        *,
        primary: bool = ...,
    ) -> _diagnostics_DiagnosticLabel: ...
    @property
    def span(self) -> _source_SourceSpan: ...
    @property
    def message(self) -> str: ...
    @property
    def message_segments(self) -> tuple[_diagnostics_DiagnosticTextSegment, ...]: ...
    @property
    def primary(self) -> bool: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _diagnostics_Diagnostic:
    def __new__(
        cls,
        severity: _diagnostics_DiagnosticSeverity,
        phase: _diagnostics_DiagnosticPhase,
        code: str,
        message: str,
        labels: Sequence[_diagnostics_DiagnosticLabel],
        notes: Sequence[str] = ...,
        *,
        styled_notes: Sequence[_diagnostics_DiagnosticStyledNote] = ...,
        word_index: int | None = ...,
    ) -> _diagnostics_Diagnostic: ...
    @property
    def severity(self) -> _diagnostics_DiagnosticSeverity: ...
    @property
    def phase(self) -> _diagnostics_DiagnosticPhase: ...
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def message_segments(self) -> tuple[_diagnostics_DiagnosticTextSegment, ...]: ...
    @property
    def labels(self) -> tuple[_diagnostics_DiagnosticLabel, ...]: ...
    @property
    def notes(self) -> tuple[str, ...]: ...
    @property
    def note_segments(self) -> tuple[tuple[_diagnostics_DiagnosticTextSegment, ...], ...]: ...
    @property
    def styled_notes(self) -> tuple[_diagnostics_DiagnosticStyledNote, ...]: ...
    @property
    def word_index(self) -> int | None: ...
    @property
    def primary_label(self) -> _diagnostics_DiagnosticLabel: ...
    def __eq__(self, value: object, /) -> bool: ...

def _diagnostics_diagnostic_text_segments(
    text: str,
) -> tuple[_diagnostics_DiagnosticTextSegment, ...]: ...
def _diagnostics_diagnostic_text_segments_text(
    segments: Sequence[_diagnostics_DiagnosticTextSegment],
) -> str: ...
def _diagnostics_trace_phase_includes(
    selector: _diagnostics_TracePhase,
    phase: _diagnostics_TracePhase,
) -> bool: ...
def _diagnostics_trace_level_number(level: _diagnostics_TraceLevel) -> int: ...
def _diagnostics_trace_level_from_number(value: int) -> _diagnostics_TraceLevel: ...
def _diagnostics_diagnostic_note_mode_visible_in(
    note_mode: _diagnostics_DiagnosticNoteMode,
    detail_mode: _diagnostics_DiagnosticDetailMode,
) -> bool: ...
