from collections.abc import Sequence
from typing import Never, final

@final
class _dialect_CmavoSwap:
    __match_args__: tuple[str, str]
    def __new__(cls, left: str, right: str) -> _dialect_CmavoSwap: ...
    @property
    def left(self) -> str: ...
    @property
    def right(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _dialect_CmavoExpansion:
    __match_args__: tuple[str, str]
    def __new__(cls, source: str, replacement: Sequence[str]) -> _dialect_CmavoExpansion: ...
    @property
    def source(self) -> str: ...
    @property
    def replacement(self) -> tuple[str, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _dialect_DialectDefinition:
    def __new__(
        cls,
        cmavo_entries: Sequence[_dialect_CmavoSwap | _dialect_CmavoExpansion] | None = ...,
        features: Sequence[_dialect_DialectFeature] | None = ...,
    ) -> _dialect_DialectDefinition: ...
    @staticmethod
    def baseline() -> _dialect_DialectDefinition: ...
    @property
    def cmavo_entries(self) -> tuple[_dialect_CmavoSwap | _dialect_CmavoExpansion, ...]: ...
    @property
    def features(self) -> tuple[_dialect_DialectFeature, ...]: ...
    def is_baseline(self) -> bool: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _dialect_BuiltinDialect:
    def __new__(cls, _nonconstructible: Never) -> _dialect_BuiltinDialect: ...
    @property
    def name(self) -> str: ...
    @property
    def definition(self) -> str: ...
    @property
    def dialect(self) -> _dialect_DialectDefinition: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _dialect_CustomDialect:
    def __new__(
        cls,
        name: str,
        definition: str,
        *,
        show_in_gentufa: bool = ...,
    ) -> _dialect_CustomDialect: ...
    @property
    def name(self) -> str: ...
    @property
    def definition(self) -> str: ...
    @property
    def show_in_gentufa(self) -> bool: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _dialect_DialectSettings:
    def __new__(
        cls,
        custom_dialects: Sequence[_dialect_CustomDialect] = ...,
        hidden_builtin_gentufa_dialects: Sequence[str] = ...,
    ) -> _dialect_DialectSettings: ...
    @property
    def custom_dialects(self) -> tuple[_dialect_CustomDialect, ...]: ...
    @property
    def hidden_builtin_gentufa_dialects(self) -> tuple[str, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

def _dialect_parse_dialect_definition(source: str) -> _dialect_DialectDefinition: ...
def _dialect_builtin_dialects() -> tuple[_dialect_BuiltinDialect, ...]: ...
def _dialect_builtin_dialect_names() -> tuple[str, ...]: ...
def _dialect_find_builtin_dialect(name: str) -> _dialect_BuiltinDialect | None: ...
def _dialect_parse_dialect_definition_with_custom_dialects(
    custom: Sequence[_dialect_CustomDialect],
    source: str,
) -> _dialect_DialectDefinition: ...
def _dialect_parse_dialect_selection_formula(
    settings: _dialect_DialectSettings,
    source: str,
) -> _dialect_DialectDefinition: ...
def _dialect_custom_dialect_is_valid(
    existing: Sequence[_dialect_CustomDialect],
    custom: _dialect_CustomDialect,
) -> None: ...
def _dialect_dialect_name_shows_in_gentufa_picker(name: str) -> bool: ...
def _dialect_dialect_formula_top_level_references(formula_text: str) -> tuple[str, ...]: ...
def _dialect_add_dialect_formula_reference(dialect_name: str, formula_text: str) -> str: ...
def _dialect_remove_dialect_formula_reference(dialect_name: str, formula_text: str) -> str: ...
def _dialect_replace_dialect_formula_reference(
    previous_name: str,
    next_name: str,
    formula_text: str,
) -> str: ...
def _dialect_dialect_definition_to_text(definition: _dialect_DialectDefinition) -> str: ...
def _dialect_cmavo_dialect_entries_to_definition(
    entries: Sequence[_dialect_CmavoSwap | _dialect_CmavoExpansion],
) -> str: ...
def _dialect_custom_dialect_definition_to_johau_uri(definition: str) -> str: ...
def _dialect_custom_dialect_definition_to_johau_uri_with_custom_dialects(
    custom: Sequence[_dialect_CustomDialect],
    definition: str,
) -> str: ...
def _dialect_dialect_definition_to_johau_uri(definition: _dialect_DialectDefinition) -> str: ...
def _dialect_parse_johau_dialect_uri(raw_uri: str) -> _dialect_DialectDefinition: ...
def _dialect_import_johau_dialect_settings(
    raw_uri: str,
    settings: _dialect_DialectSettings,
) -> tuple[str, _dialect_DialectSettings]: ...
def _dialect_dialect_feature_atom_name(feature: _dialect_DialectFeature) -> str: ...
