from collections.abc import Sequence
from typing import final

@final
class _jvozba_Word:
    __match_args__: tuple[str]
    def __new__(cls, value: str) -> _jvozba_Word: ...
    @property
    def value(self) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

@final
class _jvozba_FixedRafsi:
    __match_args__: tuple[str]
    def __new__(cls, value: str) -> _jvozba_FixedRafsi: ...
    @property
    def value(self) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

@final
class _jvozba_JvozbaSegment:
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        kind: _jvozba_JvozbaSegmentKind,
        text: str,
    ) -> _jvozba_JvozbaSegment: ...
    @property
    def kind(self) -> _jvozba_JvozbaSegmentKind: ...
    @property
    def text(self) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_JvozbaBuildResult:
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        word: str,
        segments: Sequence[_jvozba_JvozbaSegment],
    ) -> _jvozba_JvozbaBuildResult: ...
    @property
    def word(self) -> str: ...
    @property
    def segments(self) -> tuple[_jvozba_JvozbaSegment, ...]: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_LujvoSegmentInfo:
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        segment: _morphology_LujvoRafsi | _morphology_LujvoHyphen,
        source: str | None = ...,
    ) -> _jvozba_LujvoSegmentInfo: ...
    @property
    def segment(self) -> _morphology_LujvoRafsi | _morphology_LujvoHyphen: ...
    @property
    def source(self) -> str | None: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_LujvoDecomposition:
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        segments: Sequence[_jvozba_LujvoSegmentInfo],
        source_words: Sequence[str],
    ) -> _jvozba_LujvoDecomposition: ...
    @property
    def segments(self) -> tuple[_jvozba_LujvoSegmentInfo, ...]: ...
    @property
    def source_words(self) -> tuple[str, ...]: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_RequiresAtLeastTwoInputs:
    __match_args__: tuple[()]
    def __new__(cls) -> _jvozba_RequiresAtLeastTwoInputs: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_FixedRafsiEmpty:
    __match_args__: tuple[()]
    def __new__(cls) -> _jvozba_FixedRafsiEmpty: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_NonFinalUniversalLongRafsi:
    __match_args__: tuple[str]
    def __new__(cls, offending: str) -> _jvozba_NonFinalUniversalLongRafsi: ...
    @property
    def offending(self) -> str: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_FinalConsonant:
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        offending: str,
        is_fixed_rafsi: bool,
    ) -> _jvozba_FinalConsonant: ...
    @property
    def offending(self) -> str: ...
    @property
    def is_fixed_rafsi(self) -> bool: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_NoRafsiAvailable:
    __match_args__: tuple[str]
    def __new__(cls, offending: str) -> _jvozba_NoRafsiAvailable: ...
    @property
    def offending(self) -> str: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_NoDictionaryEntry:
    __match_args__: tuple[str]
    def __new__(cls, offending: str) -> _jvozba_NoDictionaryEntry: ...
    @property
    def offending(self) -> str: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_CouldNotBuildLujvo:
    __match_args__: tuple[()]
    def __new__(cls) -> _jvozba_CouldNotBuildLujvo: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _jvozba_CouldNotBuildCompound:
    __match_args__: tuple[()]
    def __new__(cls) -> _jvozba_CouldNotBuildCompound: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

def _jvozba_build_best_jvozba_detailed(
    mode: _jvozba_JvozbaMode,
    dictionary: _dictionary_Dictionary,
    raw_inputs: Sequence[_jvozba_Word | _jvozba_FixedRafsi],
) -> _jvozba_JvozbaBuildResult: ...

def _jvozba_word_can_enter_jvozba_pane(
    dictionary: _dictionary_Dictionary,
    word_text: str,
) -> bool: ...

def _jvozba_decompose_lujvo_like(
    dictionary: _dictionary_Dictionary,
    raw_word: str,
) -> _jvozba_LujvoDecomposition | None: ...
