from collections.abc import Sequence
from typing import Final, Never, final

_morphology_MORPHOLOGY_TRACE_FILTERS: Final[tuple[str, ...]]
_morphology_PERMISSIVE_IGNORABLE_RESERVED_CHARACTERS: Final[tuple[str, ...]]

@final
class _morphology_PhonemeRenderOptions:
    def __new__(
        cls,
        *,
        mark_stress: _morphology_StressMark | None = ...,
        mark_glides: _morphology_GlideMark | None = ...,
    ) -> _morphology_PhonemeRenderOptions: ...
    @property
    def mark_stress(self) -> _morphology_StressMark: ...
    @property
    def mark_glides(self) -> _morphology_GlideMark: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_Phonemes:
    def __new__(cls, text: str) -> _morphology_Phonemes: ...
    @property
    def text(self) -> str: ...
    def render(self, /, options: _morphology_PhonemeRenderOptions) -> str: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

@final
class _morphology_WordKey:
    def __new__(
        cls,
        kind: _morphology_WordKind,
        phonemes: _morphology_Phonemes,
    ) -> _morphology_WordKey: ...
    @property
    def kind(self) -> _morphology_WordKind: ...
    @property
    def phonemes(self) -> _morphology_Phonemes: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

@final
class _morphology_InvalidDialectWord:
    __match_args__: tuple[str]
    def __new__(cls, word: str) -> _morphology_InvalidDialectWord: ...
    @property
    def word(self) -> str: ...
    def __str__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self, /) -> int: ...

@final
class _morphology_CompiledDialectWord:
    def __new__(cls, _nonconstructible: Never) -> _morphology_CompiledDialectWord: ...
    @property
    def word(self) -> _MorphologyWord: ...
    @property
    def key(self) -> _morphology_WordKey: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_CompiledDialectSwap:
    __match_args__: tuple[str, str]
    def __new__(cls, _nonconstructible: Never) -> _morphology_CompiledDialectSwap: ...
    @property
    def left(self) -> _morphology_CompiledDialectWord: ...
    @property
    def right(self) -> _morphology_CompiledDialectWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_CompiledDialectExpansion:
    __match_args__: tuple[str, str]
    def __new__(cls, _nonconstructible: Never) -> _morphology_CompiledDialectExpansion: ...
    @property
    def source(self) -> _morphology_CompiledDialectWord: ...
    @property
    def replacement(self) -> tuple[_morphology_CompiledDialectWord, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_CompiledDialectDefinition:
    def __new__(
        cls,
        definition: _dialect_DialectDefinition | None = ...,
    ) -> _morphology_CompiledDialectDefinition: ...
    @property
    def entries(self) -> tuple[_morphology_CompiledDialectSwap | _morphology_CompiledDialectExpansion, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_MorphologyOptions:
    def __new__(
        cls,
        *,
        accept_latin: bool = ...,
        accept_cyrillic: bool = ...,
        accept_zbalermorna: bool = ...,
        dialect: _dialect_DialectDefinition | None = ...,
        cmevla_as_relation_words: bool = ...,
        permissive_lexer: bool = ...,
        uppercase_marks_stress: bool = ...,
        max_recovery_errors: int = ...,
        trace: _diagnostics_TraceOptions | None = ...,
    ) -> _morphology_MorphologyOptions: ...
    @staticmethod
    def default() -> _morphology_MorphologyOptions: ...
    def with_compiled_dialect(
        self, /, dialect: _morphology_CompiledDialectDefinition
    ) -> _morphology_MorphologyOptions: ...
    def with_dialect(
        self, /, dialect: _dialect_DialectDefinition
    ) -> _morphology_MorphologyOptions: ...
    def with_trace(
        self, /, trace: _diagnostics_TraceOptions
    ) -> _morphology_MorphologyOptions: ...
    def with_max_recovery_errors(self, /, max_recovery_errors: int) -> _morphology_MorphologyOptions: ...
    @property
    def accept_latin(self) -> bool: ...
    @property
    def accept_cyrillic(self) -> bool: ...
    @property
    def accept_zbalermorna(self) -> bool: ...
    @property
    def compiled_dialect(self) -> _morphology_CompiledDialectDefinition: ...
    @property
    def cmevla_as_relation_words(self) -> bool: ...
    @property
    def permissive_lexer(self) -> bool: ...
    @property
    def uppercase_marks_stress(self) -> bool: ...
    @property
    def max_recovery_errors(self) -> int: ...
    @property
    def trace(self) -> _diagnostics_TraceOptions: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_LujvoRafsi:
    __match_args__: tuple[str]
    def __new__(cls, phonemes: _morphology_Phonemes) -> _morphology_LujvoRafsi: ...
    @property
    def phonemes(self) -> _morphology_Phonemes: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_LujvoHyphen:
    __match_args__: tuple[str]
    def __new__(cls, phonemes: _morphology_Phonemes) -> _morphology_LujvoHyphen: ...
    @property
    def phonemes(self) -> _morphology_Phonemes: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_Verbatim:
    __match_args__: tuple[str, str]
    def __new__(cls, span: _source_SourceSpan, text: str) -> _morphology_Verbatim: ...
    @property
    def span(self) -> _source_SourceSpan: ...
    @property
    def text(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

class _MorphologyWordBase:
    @property
    def kind(self) -> _morphology_WordKind: ...
    @property
    def phonemes(self) -> _morphology_Phonemes: ...
    @property
    def span(self) -> _source_SourceSpan: ...
    @property
    def key(self) -> _morphology_WordKey: ...
    @property
    def canonical_phonemes(self) -> str: ...
    @property
    def cmavo(self) -> _morphology_Cmavo | None: ...
    @property
    def selmaho(self) -> _morphology_Selmaho | None: ...
    def is_cmavo(self, /, cmavo: _morphology_Cmavo) -> bool: ...
    def is_selmaho(self, /, selmaho: _morphology_Selmaho) -> bool: ...

@final
class _morphology_CmavoWord(_MorphologyWordBase):
    __match_args__: tuple[str, str]
    def __new__(cls, phonemes: _morphology_Phonemes, span: _source_SourceSpan) -> _morphology_CmavoWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_GismuWord(_MorphologyWordBase):
    __match_args__: tuple[str, str]
    def __new__(cls, phonemes: _morphology_Phonemes, span: _source_SourceSpan) -> _morphology_GismuWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_FuhivlaWord(_MorphologyWordBase):
    __match_args__: tuple[str, str]
    def __new__(cls, phonemes: _morphology_Phonemes, span: _source_SourceSpan) -> _morphology_FuhivlaWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_CmevlaWord(_MorphologyWordBase):
    __match_args__: tuple[str, str]
    def __new__(cls, phonemes: _morphology_Phonemes, span: _source_SourceSpan) -> _morphology_CmevlaWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_LujvoWord(_MorphologyWordBase):
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        parts: Sequence[_morphology_LujvoRafsi | _morphology_LujvoHyphen],
        span: _source_SourceSpan,
    ) -> _morphology_LujvoWord: ...
    @property
    def parts(self) -> tuple[_morphology_LujvoRafsi | _morphology_LujvoHyphen, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

_MorphologyWord = _morphology_CmavoWord | _morphology_GismuWord | _morphology_LujvoWord | _morphology_FuhivlaWord | _morphology_CmevlaWord

class _MorphologyWordLikeBase:
    @property
    def byte_range(self) -> tuple[int, int] | None: ...
    @property
    def source_spans(self) -> tuple[_source_SourceSpan, ...]: ...
    def __str__(self, /) -> str: ...

@final
class _morphology_PlainWord(_MorphologyWordLikeBase):
    __match_args__: tuple[str]
    def __new__(cls, word: _MorphologyWord) -> _morphology_PlainWord: ...
    @property
    def word(self) -> _MorphologyWord: ...
    @property
    def cmavo(self) -> _morphology_Cmavo | None: ...
    def is_cmavo(self, /, cmavo: _morphology_Cmavo) -> bool: ...
    def is_selmaho(self, /, selmaho: _morphology_Selmaho) -> bool: ...
    def is_brivla(self, /) -> bool: ...
    def is_cmevla(self, /) -> bool: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_QuotedWord(_MorphologyWordLikeBase):
    __match_args__: tuple[str, str]
    def __new__(cls, zo: _MorphologyWord, word: _MorphologyWord) -> _morphology_QuotedWord: ...
    @property
    def zo(self) -> _MorphologyWord: ...
    @property
    def word(self) -> _MorphologyWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_SelmahoQuotedWord(_MorphologyWordLikeBase):
    __match_args__: tuple[str, str]
    def __new__(cls, mahoi: _MorphologyWord, word: _MorphologyWord) -> _morphology_SelmahoQuotedWord: ...
    @property
    def mahoi(self) -> _MorphologyWord: ...
    @property
    def word(self) -> _MorphologyWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_DelimitedNonLojbanQuote(_MorphologyWordLikeBase):
    __match_args__: tuple[str, str, str, str]
    def __new__(
        cls,
        zoi: _MorphologyWord,
        opening_delimiter: _MorphologyWord,
        quoted_text: _morphology_Verbatim,
        closing_delimiter: _MorphologyWord,
    ) -> _morphology_DelimitedNonLojbanQuote: ...
    @property
    def zoi(self) -> _MorphologyWord: ...
    @property
    def opening_delimiter(self) -> _MorphologyWord: ...
    @property
    def quoted_text(self) -> _morphology_Verbatim: ...
    @property
    def closing_delimiter(self) -> _MorphologyWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_QuotedWords(_MorphologyWordLikeBase):
    __match_args__: tuple[str, str, str]
    def __new__(
        cls,
        lohu: _MorphologyWord,
        quoted_words: Sequence[_MorphologyWord],
        lehu: _MorphologyWord,
    ) -> _morphology_QuotedWords: ...
    @property
    def lohu(self) -> _MorphologyWord: ...
    @property
    def quoted_words(self) -> tuple[_MorphologyWord, ...]: ...
    @property
    def lehu(self) -> _MorphologyWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_DelimitedWordQuote(_MorphologyWordLikeBase):
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        marker: _MorphologyWord,
        quoted_text: _morphology_Verbatim,
    ) -> _morphology_DelimitedWordQuote: ...
    @property
    def marker(self) -> _MorphologyWord: ...
    @property
    def quoted_text(self) -> _morphology_Verbatim: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_LerfuWord(_MorphologyWordLikeBase):
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        base: _MorphologyWordLike,
        bu: _MorphologyWord,
    ) -> _morphology_LerfuWord: ...
    @property
    def base(self) -> _MorphologyWordLike: ...
    @property
    def bu(self) -> _MorphologyWord: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_ZeiCompound(_MorphologyWordLikeBase):
    __match_args__: tuple[str, str, str]
    def __new__(
        cls,
        left: _MorphologyWordLike,
        zei: _MorphologyWord,
        right: _MorphologyWord,
    ) -> _morphology_ZeiCompound: ...
    @property
    def left(self) -> _MorphologyWordLike: ...
    @property
    def zei(self) -> _MorphologyWord: ...
    @property
    def right(self) -> _MorphologyWord: ...
    def __eq__(self, value: object, /) -> bool: ...

_MorphologyWordLike = _morphology_PlainWord | _morphology_QuotedWord | _morphology_SelmahoQuotedWord | _morphology_DelimitedNonLojbanQuote | _morphology_QuotedWords | _morphology_DelimitedWordQuote | _morphology_LerfuWord | _morphology_ZeiCompound

@final
class _morphology_MorphologyContext:
    __match_args__: tuple[str, str, str]
    def __new__(
        cls,
        kind: _morphology_MorphologyContextKind,
        char_start: int,
        char_end: int,
    ) -> _morphology_MorphologyContext: ...
    @property
    def kind(self) -> _morphology_MorphologyContextKind: ...
    @property
    def char_start(self) -> int: ...
    @property
    def char_end(self) -> int: ...
    @property
    def label(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_InvalidLujvoDetail:
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        expected: _morphology_LujvoParseExpectation,
        parsed_prefix: str | None = ...,
    ) -> _morphology_InvalidLujvoDetail: ...
    @property
    def parsed_prefix(self) -> str | None: ...
    @property
    def expected(self) -> _morphology_LujvoParseExpectation: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_FuhivlaContainsYDetail:
    __match_args__: tuple[()]
    def __new__(cls) -> _morphology_FuhivlaContainsYDetail: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_SlinkuhiDetail:
    __match_args__: tuple[()]
    def __new__(cls) -> _morphology_SlinkuhiDetail: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_ExpectedWordDetail:
    __match_args__: tuple[str]
    def __new__(cls, expected: _morphology_ExpectedWordDetailKind) -> _morphology_ExpectedWordDetail: ...
    @property
    def expected(self) -> _morphology_ExpectedWordDetailKind: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_InvalidZoiDelimiterDetail:
    __match_args__: tuple[str]
    def __new__(cls, reason: _morphology_ZoiDelimiterDetailKind) -> _morphology_InvalidZoiDelimiterDetail: ...
    @property
    def reason(self) -> _morphology_ZoiDelimiterDetailKind: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_PhonotacticDetail:
    __match_args__: tuple[str]
    def __new__(cls, reason: _morphology_PhonotacticDetailKind) -> _morphology_PhonotacticDetail: ...
    @property
    def reason(self) -> _morphology_PhonotacticDetailKind: ...
    def __eq__(self, value: object, /) -> bool: ...

_MorphologyErrorDetail = _morphology_InvalidLujvoDetail | _morphology_FuhivlaContainsYDetail | _morphology_SlinkuhiDetail | _morphology_ExpectedWordDetail | _morphology_InvalidZoiDelimiterDetail | _morphology_PhonotacticDetail

@final
class _morphology_MorphologyWarning:
    __match_args__: tuple[str, str, str, str, str, str]
    def __new__(
        cls,
        kind: _morphology_MorphologyWarningKind,
        char_start: int,
        char_end: int,
        text: str,
        *,
        context: _morphology_MorphologyContext | None = ...,
        ignored_character_count: int | None = ...,
    ) -> _morphology_MorphologyWarning: ...
    @property
    def kind(self) -> _morphology_MorphologyWarningKind: ...
    @property
    def code(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def char_start(self) -> int: ...
    @property
    def char_end(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def context(self) -> _morphology_MorphologyContext | None: ...
    @property
    def ignored_character_count(self) -> int | None: ...
    def to_diagnostic(
        self,
        /,
        source: str,
        source_id: _source_SourceId | None = ...,
    ) -> _diagnostics_Diagnostic: ...
    def __eq__(self, value: object, /) -> bool: ...

class _MorphologyErrorValueBase:
    @property
    def code(self) -> str: ...
    def to_diagnostic(
        self,
        /,
        source: str,
        source_id: _source_SourceId | None = ...,
    ) -> _diagnostics_Diagnostic: ...
    def __str__(self, /) -> str: ...

@final
class _morphology_InvalidMorphology(_MorphologyErrorValueBase):
    __match_args__: tuple[str, str, str, str, str, str]
    def __new__(
        cls,
        kind: _morphology_MorphologyErrorKind,
        char_start: int,
        char_end: int,
        text: str,
        *,
        context: _morphology_MorphologyContext | None = ...,
        detail: _MorphologyErrorDetail | None = ...,
    ) -> _morphology_InvalidMorphology: ...
    @property
    def kind(self) -> _morphology_MorphologyErrorKind: ...
    @property
    def message(self) -> str: ...
    @property
    def char_start(self) -> int: ...
    @property
    def char_end(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def context(self) -> _morphology_MorphologyContext | None: ...
    @property
    def detail(self) -> _MorphologyErrorDetail | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_UnterminatedZoiQuote(_MorphologyErrorValueBase):
    __match_args__: tuple[str, str, str]
    def __new__(
        cls,
        char_offset: int,
        delimiter: str,
        *,
        context: _morphology_MorphologyContext | None = ...,
    ) -> _morphology_UnterminatedZoiQuote: ...
    @property
    def char_offset(self) -> int: ...
    @property
    def delimiter(self) -> str: ...
    @property
    def context(self) -> _morphology_MorphologyContext | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_SourceSpanMorphologyError(_MorphologyErrorValueBase):
    __match_args__: tuple[str]
    def __new__(
        cls,
        error: _source_ZeroLine | _source_ZeroColumn | _source_ByteRangeInverted | _source_CharRangeInverted,
    ) -> _morphology_SourceSpanMorphologyError: ...
    @property
    def error(self) -> _source_ZeroLine | _source_ZeroColumn | _source_ByteRangeInverted | _source_CharRangeInverted: ...
    def __eq__(self, value: object, /) -> bool: ...

_MorphologyErrorValue = _morphology_InvalidMorphology | _morphology_UnterminatedZoiQuote | _morphology_SourceSpanMorphologyError

@final
class _morphology_MorphologySegmentAttempt:
    def __new__(cls, _nonconstructible: Never) -> _morphology_MorphologySegmentAttempt: ...
    @property
    def source(self) -> str: ...
    @property
    def source_id(self) -> _source_SourceId | None: ...
    @property
    def succeeded(self) -> bool: ...
    @property
    def words(self) -> tuple[_MorphologyWordLike, ...] | None: ...
    @property
    def error(self) -> _MorphologyErrorValue | None: ...
    @property
    def warnings(self) -> tuple[_morphology_MorphologyWarning, ...]: ...
    @property
    def trace(self) -> _diagnostics_TraceReport | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_RecoveredMorphologySegmentation:
    def __new__(cls, _nonconstructible: Never) -> _morphology_RecoveredMorphologySegmentation: ...
    @property
    def words(self) -> tuple[_MorphologyWordLike, ...]: ...
    @property
    def errors(self) -> tuple[_MorphologyErrorValue, ...]: ...
    @property
    def error_regions(self) -> tuple[_source_SourceSpan, ...]: ...
    @property
    def warnings(self) -> tuple[_morphology_MorphologyWarning, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_RecoveredMorphologySegmentAttempt:
    def __new__(cls, _nonconstructible: Never) -> _morphology_RecoveredMorphologySegmentAttempt: ...
    @property
    def source(self) -> str: ...
    @property
    def source_id(self) -> _source_SourceId | None: ...
    @property
    def result(self) -> _morphology_RecoveredMorphologySegmentation: ...
    @property
    def trace(self) -> _diagnostics_TraceReport | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_ValsiLujvoPart:
    __match_args__: tuple[str, str, str]
    def __new__(
        cls,
        kind: _morphology_ValsiLujvoPartKind,
        text: str,
        *,
        rafsi_kind: _morphology_ValsiLujvoRafsiKind | None = ...,
    ) -> _morphology_ValsiLujvoPart: ...
    @property
    def kind(self) -> _morphology_ValsiLujvoPartKind: ...
    @property
    def text(self) -> str: ...
    @property
    def rafsi_kind(self) -> _morphology_ValsiLujvoRafsiKind | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_PlainWordClassification:
    __match_args__: tuple[str, str, str, str, str, str]
    def __new__(
        cls,
        category: _morphology_WordKind,
        phonemes: str,
        *,
        selmaho: str | None = ...,
        split: str | None = ...,
        parts: Sequence[_morphology_ValsiLujvoPart] = ...,
        stage: _morphology_ValsiFuhivlaStage | None = ...,
    ) -> _morphology_PlainWordClassification: ...
    @property
    def category(self) -> _morphology_WordKind: ...
    @property
    def phonemes(self) -> str: ...
    @property
    def selmaho(self) -> str | None: ...
    @property
    def split(self) -> str | None: ...
    @property
    def parts(self) -> tuple[_morphology_ValsiLujvoPart, ...]: ...
    @property
    def stage(self) -> _morphology_ValsiFuhivlaStage | None: ...
    def __eq__(self, value: object, /) -> bool: ...

class _ValsiClassificationBase:
    @property
    def kind(self) -> _morphology_ValsiClassificationKind: ...

@final
class _morphology_PlainWordValsiClassification(_ValsiClassificationBase):
    __match_args__: tuple[str]
    def __new__(cls, word: _morphology_PlainWordClassification) -> _morphology_PlainWordValsiClassification: ...
    @property
    def word(self) -> _morphology_PlainWordClassification: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_QuotedWordValsiClassification(_ValsiClassificationBase):
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        marker: _morphology_PlainWordClassification,
        quoted_word: _morphology_PlainWordClassification,
    ) -> _morphology_QuotedWordValsiClassification: ...
    @property
    def marker(self) -> _morphology_PlainWordClassification: ...
    @property
    def quoted_word(self) -> _morphology_PlainWordClassification: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_DelimitedNonLojbanQuoteValsiClassification(_ValsiClassificationBase):
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        marker: _morphology_PlainWordClassification,
        delimiter: str,
    ) -> _morphology_DelimitedNonLojbanQuoteValsiClassification: ...
    @property
    def marker(self) -> _morphology_PlainWordClassification: ...
    @property
    def delimiter(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_QuotedWordsValsiClassification(_ValsiClassificationBase):
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        marker: _morphology_PlainWordClassification,
        quoted_words: Sequence[_morphology_PlainWordClassification],
    ) -> _morphology_QuotedWordsValsiClassification: ...
    @property
    def marker(self) -> _morphology_PlainWordClassification: ...
    @property
    def quoted_words(self) -> tuple[_morphology_PlainWordClassification, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_DelimitedWordQuoteValsiClassification(_ValsiClassificationBase):
    __match_args__: tuple[str]
    def __new__(cls, marker_text: str) -> _morphology_DelimitedWordQuoteValsiClassification: ...
    @property
    def marker_text(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_LerfuWordValsiClassification(_ValsiClassificationBase):
    __match_args__: tuple[str, str]
    def __new__(
        cls,
        base: _ValsiClassification,
        suffix: _morphology_PlainWordClassification,
    ) -> _morphology_LerfuWordValsiClassification: ...
    @property
    def base(self) -> _ValsiClassification: ...
    @property
    def suffix(self) -> _morphology_PlainWordClassification: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_ZeiCompoundValsiClassification(_ValsiClassificationBase):
    __match_args__: tuple[str, str, str]
    def __new__(
        cls,
        left: _ValsiClassification,
        link: _morphology_PlainWordClassification,
        right: _morphology_PlainWordClassification,
    ) -> _morphology_ZeiCompoundValsiClassification: ...
    @property
    def left(self) -> _ValsiClassification: ...
    @property
    def link(self) -> _morphology_PlainWordClassification: ...
    @property
    def right(self) -> _morphology_PlainWordClassification: ...
    def __eq__(self, value: object, /) -> bool: ...

_ValsiClassification = _morphology_PlainWordValsiClassification | _morphology_QuotedWordValsiClassification | _morphology_DelimitedNonLojbanQuoteValsiClassification | _morphology_QuotedWordsValsiClassification | _morphology_DelimitedWordQuoteValsiClassification | _morphology_LerfuWordValsiClassification | _morphology_ZeiCompoundValsiClassification

@final
class _morphology_ValsiAnalysisResult:
    def __new__(
        cls,
        status: _morphology_ValsiAnalysisStatus,
        *,
        word: _MorphologyWordLike | None = ...,
        classification: _ValsiClassification | None = ...,
        error: _MorphologyErrorValue | None = ...,
        words: Sequence[_MorphologyWordLike] = ...,
    ) -> _morphology_ValsiAnalysisResult: ...
    @property
    def status(self) -> _morphology_ValsiAnalysisStatus: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def word(self) -> _MorphologyWordLike | None: ...
    @property
    def classification(self) -> _ValsiClassification | None: ...
    @property
    def error(self) -> _MorphologyErrorValue | None: ...
    @property
    def words(self) -> tuple[_MorphologyWordLike, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_ValsiAnalysis:
    __match_args__: tuple[str, str, str]
    def __new__(cls, _nonconstructible: Never) -> _morphology_ValsiAnalysis: ...
    @property
    def input(self) -> str: ...
    @property
    def warnings(self) -> tuple[_morphology_MorphologyWarning, ...]: ...
    @property
    def result(self) -> _morphology_ValsiAnalysisResult: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_LujvoRafsiBuildPart:
    __match_args__: tuple[str]
    def __new__(cls, text: str) -> _morphology_LujvoRafsiBuildPart: ...
    @property
    def text(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_LujvoBrivlaCoreBuildPart:
    __match_args__: tuple[str]
    def __new__(cls, text: str) -> _morphology_LujvoBrivlaCoreBuildPart: ...
    @property
    def text(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _morphology_LujvoCandidate:
    __match_args__: tuple[str, str, str]
    def __new__(cls, word: str, parts: Sequence[str], score: int) -> _morphology_LujvoCandidate: ...
    @property
    def word(self) -> str: ...
    @property
    def parts(self) -> tuple[str, ...]: ...
    @property
    def score(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

def _morphology_segment_attempt(
    source: str,
    *,
    options: _morphology_MorphologyOptions | None = ...,
    source_id: _source_SourceId | None = ...,
) -> _morphology_MorphologySegmentAttempt: ...
def _morphology_segment_recovered_attempt(
    source: str,
    *,
    options: _morphology_MorphologyOptions | None = ...,
    source_id: _source_SourceId | None = ...,
) -> _morphology_RecoveredMorphologySegmentAttempt: ...
def _morphology_segment_for_display_attempt(
    source: str,
    *,
    options: _morphology_MorphologyOptions | None = ...,
    source_id: _source_SourceId | None = ...,
) -> _morphology_MorphologySegmentAttempt: ...
def _morphology_analyze_valsi(
    source: str,
    *,
    options: _morphology_MorphologyOptions | None = ...,
    source_id: _source_SourceId | None = ...,
) -> _morphology_ValsiAnalysis: ...
def _morphology_normalize_input(
    text: str,
    *,
    options: _morphology_MorphologyOptions | None = ...,
) -> str | None: ...
def _morphology_canonicalize_text(text: str) -> str: ...
def _morphology_canonical_text_eq(left: str, right: str) -> bool: ...
def _morphology_canonical_text_is_all(text: str, expected: str) -> bool: ...
def _morphology_normalize_cmavo_form(text: str) -> str | None: ...
def _morphology_cmavo_phonemes(text: str) -> _morphology_Phonemes | None: ...
def _morphology_pronunciation_syllables(phonemes: _morphology_Phonemes) -> tuple[str, ...]: ...
def _morphology_strip_lojban_diacritic(value: str) -> str | None: ...
def _morphology_fold_lojban_diacritic(value: str) -> str | None: ...
def _morphology_strip_lojban_diacritics(text: str) -> str: ...
def _morphology_fold_lojban_diacritics(text: str) -> str: ...
def _morphology_stripped_lojban_diacritics_eq(left: str, right: str) -> bool: ...
def _morphology_folded_lojban_diacritics_eq(left: str, right: str) -> bool: ...
def _morphology_strip_diacritics(text: str) -> str: ...
def _morphology_strip_diacritics_eq(left: str, right: str) -> bool: ...
def _morphology_is_valid_phoneme(value: str) -> bool: ...
def _morphology_is_word_forming_character(
    value: str,
    *,
    options: _morphology_MorphologyOptions | None = ...,
) -> bool: ...
def _morphology_is_period_character(value: str) -> bool: ...
def _morphology_is_permissive_ignorable_character(value: str) -> bool: ...
def _morphology_parse_lujvo_parts(
    word: str,
) -> tuple[_morphology_LujvoRafsi | _morphology_LujvoHyphen, ...] | None: ...
def _morphology_parse_cmevla_lujvo_parts(
    word: str,
) -> tuple[_morphology_LujvoRafsi | _morphology_LujvoHyphen, ...] | None: ...
def _morphology_parse_cmevla_lujvo_part_candidates(
    word: str,
) -> tuple[tuple[_morphology_LujvoRafsi | _morphology_LujvoHyphen, ...], ...]: ...
def _morphology_bond_rafsis(rafsis: Sequence[str]) -> tuple[str, ...] | None: ...
def _morphology_is_valid_lujvo_candidate_word(word: str) -> bool: ...
def _morphology_ensure_cmevla_word(word: str) -> str: ...
def _morphology_ends_with_consonant(word: str) -> bool: ...
def _morphology_ends_with_vowel(word: str) -> bool: ...
def _morphology_is_bonding_hyphen(part: str) -> bool: ...
def _morphology_syllables_pattern(text: str) -> str | None: ...
def _morphology_rafsi_shape(text: str) -> _morphology_RafsiShape: ...
def _morphology_rafsi_shape_score(shape: _morphology_RafsiShape) -> int: ...
def _morphology_is_vowel(value: str) -> bool: ...
def _morphology_is_consonant(value: str) -> bool: ...
def _morphology_is_cmevla(text: str) -> bool: ...
def _morphology_consonant_pair_class(
    first: str,
    second: str,
) -> _morphology_ConsonantPairClass | None: ...
def _morphology_permissible_consonant_pair(first: str, second: str) -> bool: ...
def _morphology_consonant_pair_is_permissible(value: _morphology_ConsonantPairClass) -> bool: ...
def _morphology_consonant_pair_is_initial(value: _morphology_ConsonantPairClass) -> bool: ...
def _morphology_word_needs_leading_pause(
    word: _MorphologyWord,
    mode: _morphology_LeadingPauseVowelMode,
) -> bool: ...
def _morphology_word_needs_leading_pause_in_context(
    word: _MorphologyWord,
    mode: _morphology_LeadingPauseVowelMode,
    context: _morphology_LeadingPauseContext,
) -> bool: ...
def _morphology_word_syntax_eq(left: _MorphologyWord, right: _MorphologyWord) -> bool: ...
def _morphology_word_like_syntax_eq(left: _MorphologyWordLike, right: _MorphologyWordLike) -> bool: ...
def _morphology_cmavo_from_text(text: str) -> _morphology_Cmavo | None: ...
def _morphology_cmavo_text(cmavo: _morphology_Cmavo) -> str: ...
def _morphology_cmavo_is_selmaho(cmavo: _morphology_Cmavo, selmaho: _morphology_Selmaho) -> bool: ...
def _morphology_cmavo_primary_selmaho(cmavo: _morphology_Cmavo) -> _morphology_Selmaho | None: ...
def _morphology_cmavo_is_quote_opener(cmavo: _morphology_Cmavo) -> bool: ...
def _morphology_cmavo_is_single_word_quote_opener(cmavo: _morphology_Cmavo) -> bool: ...
def _morphology_cmavo_is_delimited_non_lojban_quote_opener(cmavo: _morphology_Cmavo) -> bool: ...
def _morphology_selmaho_from_name(name: str) -> _morphology_Selmaho | None: ...
def _morphology_selmaho_name(selmaho: _morphology_Selmaho) -> str: ...
def _morphology_selmaho_contains(selmaho: _morphology_Selmaho, cmavo: _morphology_Cmavo) -> bool: ...
def _morphology_choose_best_lujvo_candidate(
    mode: _morphology_LujvoBuildMode,
    choices: Sequence[Sequence[str]],
) -> _morphology_LujvoCandidate | None: ...
def _morphology_choose_best_lujvo_candidate_from_parts(
    mode: _morphology_LujvoBuildMode,
    choices: Sequence[Sequence[_morphology_LujvoRafsiBuildPart | _morphology_LujvoBrivlaCoreBuildPart]],
) -> _morphology_LujvoCandidate | None: ...
