from typing import ClassVar, Final, TypeAlias, final

from .semantics.references import (
    ReferenceFixtureProjection as _ReferenceFixtureProjection,
    SyntaxNode as _ReferenceSyntaxNode,
)
from .syntax.strict import (
    AbstractionTanruUnitSyntax as _StrictAbstractionSyntax,
    BridiSyntax as _StrictBridiSyntax,
    BridiTailSyntax as _StrictBridiTailSyntax,
    FreeModifierSyntax as _StrictFreeModifierSyntax,
    MeksoOperatorSyntax as _StrictMeksoOperatorSyntax,
    MeksoSyntax as _StrictMeksoSyntax,
    ParagraphSyntax as _StrictParagraphSyntax,
    SelbriSyntax as _StrictSelbriSyntax,
    StatementSyntax as _StrictStatementSyntax,
    SumtiSyntax as _StrictSumtiSyntax,
    TanruUnitSyntax as _StrictTanruUnitSyntax,
    TermSyntax as _StrictTermSyntax,
    TextSyntax as _StrictReferenceTextSyntax,
)
_references_RUNTIME_INVENTORY: Final[tuple[str, ...]]

@final
class _references_RawSyntaxNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_TextNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_ParagraphNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_StatementNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_BridiNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_BridiTailNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_SelbriNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_TanruUnitNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_TermNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_SumtiNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_FreeModifierNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_AbstractionNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_MeksoNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_MeksoOperatorNodeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    @property
    def raw_id(self) -> _references_RawSyntaxNodeId: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_SelbriPlaceFrameId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_SumtiPlaceAssignmentId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_ReferenceEdgeId:
    __match_args__: ClassVar[tuple[str]]
    @property
    def value(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_SyntaxNodeMetadata:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str, str, str, str, str, str, str, str]]
    @property
    def id(self) -> _references_RawSyntaxNodeId: ...
    @property
    def parent(self) -> _references_RawSyntaxNodeId | None: ...
    @property
    def preorder(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def leaf_start(self) -> int: ...
    @property
    def leaf_end(self) -> int: ...
    @property
    def first_source_span(self) -> _source_SourceSpan | None: ...
    @property
    def last_source_span(self) -> _source_SourceSpan | None: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_NumberedPlaceSlot:
    __match_args__: ClassVar[tuple[str]]
    def __new__(cls, place: int) -> _references_NumberedPlaceSlot: ...
    @property
    def place(self) -> int: ...
    def numbered_index(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_ModalPlaceSlot:
    __match_args__: ClassVar[tuple[str]]
    def __new__(
        cls, tag: _references_RawSyntaxNodeId | None = ...
    ) -> _references_ModalPlaceSlot: ...
    @property
    def tag(self) -> _references_RawSyntaxNodeId | None: ...
    def numbered_index(self) -> None: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_PlaceQuestionPlaceSlot:
    __match_args__: ClassVar[tuple[()]]
    def __new__(cls) -> _references_PlaceQuestionPlaceSlot: ...
    def numbered_index(self) -> None: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_FaiPlaceSlot:
    __match_args__: ClassVar[tuple[()]]
    def __new__(cls) -> _references_FaiPlaceSlot: ...
    def numbered_index(self) -> None: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

_PlaceFramePropagation: TypeAlias = (
    _references_NoPlaceFramePropagation
    | _references_ForwardPlaceFramePropagation
    | _references_ConversionPlaceFramePropagation
    | _references_JaiPlaceFramePropagation
    | _references_ConnectiveBranchesPlaceFramePropagation
    | _references_CompoundPlaceFramePropagation
    | _references_CoPlaceFramePropagation
)

@final
class _references_NoPlaceFramePropagation:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[()]]
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_ForwardPlaceFramePropagation:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str]]
    @property
    def inner(self) -> _references_SelbriPlaceFrameId: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_ConversionPlaceFramePropagation:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str, str]]
    @property
    def inner(self) -> _references_SelbriPlaceFrameId: ...
    @property
    def converted_place(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_JaiPlaceFramePropagation:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str]]
    @property
    def inner(self) -> _references_SelbriPlaceFrameId: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_ConnectiveBranchesPlaceFramePropagation:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str]]
    @property
    def branches(self) -> tuple[_references_SelbriPlaceFrameId, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_CompoundPlaceFramePropagation:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str, str]]
    @property
    def head(self) -> _references_SelbriPlaceFrameId: ...
    @property
    def modifiers(self) -> tuple[_references_SelbriPlaceFrameId, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_CoPlaceFramePropagation:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str, str]]
    @property
    def leading(self) -> _references_SelbriPlaceFrameId: ...
    @property
    def trailing(self) -> _references_SelbriPlaceFrameId: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_SelbriPlaceFrame:
    __match_args__: ClassVar[tuple[str, str, str, str, str, str]]
    @property
    def id(self) -> _references_SelbriPlaceFrameId: ...
    @property
    def node(self) -> _references_RawSyntaxNodeId: ...
    @property
    def kind(self) -> _references_PlaceFrameKind: ...
    @property
    def selbri(self) -> _references_SelbriNodeId | None: ...
    @property
    def tanru_unit(self) -> _references_TanruUnitNodeId | None: ...
    @property
    def propagation(self) -> _PlaceFramePropagation: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

_PlaceSlot: TypeAlias = (
    _references_NumberedPlaceSlot
    | _references_ModalPlaceSlot
    | _references_PlaceQuestionPlaceSlot
    | _references_FaiPlaceSlot
)

@final
class _references_SumtiPlaceAssignment:
    __match_args__: ClassVar[tuple[str, str, str, str, str, str]]
    @property
    def id(self) -> _references_SumtiPlaceAssignmentId: ...
    @property
    def frame(self) -> _references_SelbriPlaceFrameId: ...
    @property
    def slot(self) -> _PlaceSlot: ...
    @property
    def sumti(self) -> _references_SumtiNodeId: ...
    @property
    def term(self) -> _references_TermNodeId | None: ...
    @property
    def source(self) -> _references_AssignmentSource: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_ResolvedNodeReferenceTarget:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str]]
    @property
    def node(self) -> _references_RawSyntaxNodeId: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_ResolvedFrameReferenceTarget:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str]]
    @property
    def frame(self) -> _references_SelbriPlaceFrameId: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_AmbiguousNodesReferenceTarget:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str]]
    @property
    def nodes(self) -> tuple[_references_RawSyntaxNodeId, ...]: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_UnresolvedReferenceTarget:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str]]
    @property
    def reason(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class _references_VagueReferenceTarget:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    __match_args__: ClassVar[tuple[str]]
    @property
    def kind(self) -> _references_VagueReferenceKind: ...
    def __eq__(self, value: object, /) -> bool: ...

_ReferenceTarget: TypeAlias = (
    _references_ResolvedNodeReferenceTarget
    | _references_ResolvedFrameReferenceTarget
    | _references_AmbiguousNodesReferenceTarget
    | _references_UnresolvedReferenceTarget
    | _references_VagueReferenceTarget
)

@final
class _references_ReferenceEdge:
    __match_args__: ClassVar[tuple[str, str, str, str, str]]
    @property
    def id(self) -> _references_ReferenceEdgeId: ...
    @property
    def kind(self) -> _references_ReferenceKind: ...
    @property
    def source(self) -> _references_RawSyntaxNodeId: ...
    @property
    def target(self) -> _ReferenceTarget: ...
    @property
    def rule(self) -> _references_ReferenceRule: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_MissingRootNode:
    __match_args__: ClassVar[tuple[()]]
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _references_GeneratedSyntaxIndex:
    def root(self) -> _references_TextNodeId: ...
    def node_count(self) -> int: ...
    def node(
        self, id: _references_RawSyntaxNodeId
    ) -> _ReferenceSyntaxNode | None: ...
    def metadata(
        self, id: _references_RawSyntaxNodeId
    ) -> _references_SyntaxNodeMetadata | None: ...
    def id_of(
        self, node: _ReferenceSyntaxNode
    ) -> _references_RawSyntaxNodeId | None: ...
    def text_node_id(
        self, node: _StrictReferenceTextSyntax
    ) -> _references_TextNodeId | None: ...
    def paragraph_node_id(
        self, node: _StrictParagraphSyntax
    ) -> _references_ParagraphNodeId | None: ...
    def statement_node_id(
        self, node: _StrictStatementSyntax
    ) -> _references_StatementNodeId | None: ...
    def bridi_node_id(
        self, node: _StrictBridiSyntax
    ) -> _references_BridiNodeId | None: ...
    def bridi_tail_node_id(
        self, node: _StrictBridiTailSyntax
    ) -> _references_BridiTailNodeId | None: ...
    def selbri_node_id(
        self, node: _StrictSelbriSyntax
    ) -> _references_SelbriNodeId | None: ...
    def tanru_unit_node_id(
        self, node: _StrictTanruUnitSyntax
    ) -> _references_TanruUnitNodeId | None: ...
    def term_node_id(
        self, node: _StrictTermSyntax
    ) -> _references_TermNodeId | None: ...
    def sumti_node_id(
        self, node: _StrictSumtiSyntax
    ) -> _references_SumtiNodeId | None: ...
    def free_modifier_node_id(
        self, node: _StrictFreeModifierSyntax
    ) -> _references_FreeModifierNodeId | None: ...
    def abstraction_node_id(
        self, node: _StrictAbstractionSyntax
    ) -> _references_AbstractionNodeId | None: ...
    def mekso_node_id(
        self, node: _StrictMeksoSyntax
    ) -> _references_MeksoNodeId | None: ...
    def mekso_operator_node_id(
        self, node: _StrictMeksoOperatorSyntax
    ) -> _references_MeksoOperatorNodeId | None: ...

@final
class _references_PlaceAnalysis:
    def frames(self) -> tuple[_references_SelbriPlaceFrame, ...]: ...
    def frame(
        self, id: _references_SelbriPlaceFrameId
    ) -> _references_SelbriPlaceFrame | None: ...
    def frames_for_node(
        self, node: _references_RawSyntaxNodeId
    ) -> tuple[_references_SelbriPlaceFrameId, ...]: ...
    def assignments(
        self,
    ) -> tuple[_references_SumtiPlaceAssignment, ...]: ...
    def assignment(
        self, id: _references_SumtiPlaceAssignmentId
    ) -> _references_SumtiPlaceAssignment | None: ...
    def assignments_for_sumti(
        self, sumti: _references_SumtiNodeId
    ) -> tuple[_references_SumtiPlaceAssignmentId, ...]: ...
    def assignments_for_term(
        self, term: _references_TermNodeId
    ) -> tuple[_references_SumtiPlaceAssignmentId, ...]: ...
    def assignments_for_frame(
        self, frame: _references_SelbriPlaceFrameId
    ) -> tuple[_references_SumtiPlaceAssignmentId, ...]: ...
    def assignments_for_frame_slot(
        self, frame: _references_SelbriPlaceFrameId, slot: _PlaceSlot
    ) -> tuple[_references_SumtiPlaceAssignmentId, ...]: ...
    def first_argument_for_place(
        self, frame: _references_SelbriPlaceFrameId, slot: _PlaceSlot
    ) -> _references_SumtiNodeId | None: ...

@final
class _references_DiscourseReferences:
    def edges(self) -> tuple[_references_ReferenceEdge, ...]: ...

@final
class _references_ReferenceAnalysis:
    @property
    def syntax(self) -> _StrictReferenceTextSyntax: ...
    @property
    def syntax_index(self) -> _references_GeneratedSyntaxIndex: ...
    @property
    def place_analysis(self) -> _references_PlaceAnalysis: ...
    @property
    def discourse_references(self) -> _references_DiscourseReferences: ...
    def fixture_projection(self) -> _ReferenceFixtureProjection: ...
    def fixture_projection_json(self) -> str: ...

def _references_analyze_references(
    tree_or_parse: _StrictReferenceTextSyntax | _syntax_parser_SyntaxParse,
) -> _references_ReferenceAnalysis: ...
