from typing import final

@final
class _source_SourceId:
    def __new__(cls, value: str) -> _source_SourceId: ...
    @property
    def value(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _source_LineColumn:
    def __new__(cls, line: int, column: int) -> _source_LineColumn: ...
    @property
    def line(self) -> int: ...
    @property
    def column(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _source_SourceSpan:
    def __new__(
        cls,
        byte_start: int,
        byte_end: int,
        char_start: int,
        char_end: int,
        *,
        source_id: _source_SourceId | None = ...,
        start: _source_LineColumn | None = ...,
        end: _source_LineColumn | None = ...,
    ) -> _source_SourceSpan: ...
    @property
    def source_id(self) -> _source_SourceId | None: ...
    @property
    def byte_start(self) -> int: ...
    @property
    def byte_end(self) -> int: ...
    @property
    def char_start(self) -> int: ...
    @property
    def char_end(self) -> int: ...
    @property
    def start(self) -> _source_LineColumn | None: ...
    @property
    def end(self) -> _source_LineColumn | None: ...
    @property
    def byte_range(self) -> tuple[int, int]: ...
    @property
    def char_range(self) -> tuple[int, int]: ...
    @property
    def byte_len(self) -> int: ...
    @property
    def char_len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class _source_ZeroLine:
    __match_args__: tuple[()]
    def __new__(cls) -> _source_ZeroLine: ...
    def __eq__(self, other: object) -> bool: ...

@final
class _source_ZeroColumn:
    __match_args__: tuple[()]
    def __new__(cls) -> _source_ZeroColumn: ...
    def __eq__(self, other: object) -> bool: ...

@final
class _source_ByteRangeInverted:
    __match_args__: tuple[str, str]
    def __new__(cls, start: int, end: int) -> _source_ByteRangeInverted: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class _source_CharRangeInverted:
    __match_args__: tuple[str, str]
    def __new__(cls, start: int, end: int) -> _source_CharRangeInverted: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

def _source_source_span_from_char_offsets(
    source: str,
    char_start: int,
    char_end: int,
    *,
    source_id: _source_SourceId | None = ...,
) -> _source_SourceSpan: ...
def _source_source_span_from_byte_offsets(
    source: str,
    byte_start: int,
    byte_end: int,
    *,
    source_id: _source_SourceId | None = ...,
) -> _source_SourceSpan: ...
def _source_byte_offset_for_char_offset(source: str, char_offset: int) -> int: ...
def _source_char_offset_for_byte_offset(source: str, byte_offset: int) -> int: ...
def _source_line_column_for_byte_offset(source: str, byte_offset: int) -> _source_LineColumn: ...
def _source_source_text_for_span(source: str, span: _source_SourceSpan) -> str: ...
