from collections.abc import Sequence
from typing import ClassVar, final

_syntax_STRICT_SOURCE: str
_syntax_RECOVERED_SOURCE: str
_syntax_STRICT_STUB: str
_syntax_RECOVERED_STUB: str
_syntax_STRICT_INVENTORY: tuple[str, ...]
_syntax_RECOVERED_INVENTORY: tuple[str, ...]
_syntax_STRICT_CONCRETE_INVENTORY: tuple[str, ...]
_syntax_RECOVERED_CONCRETE_INVENTORY: tuple[str, ...]
_syntax_SCHEMA_MODEL_COUNT: int
_syntax_SCHEMA_VARIANT_COUNT: int
_syntax_SCHEMA_FIELD_COUNT: int

@final
class _syntax_Value:
    def _field(self, index: int) -> object: ...
    def _same_identity(self, other: _syntax_Value) -> bool: ...
    def _structural_eq(self, other: _syntax_Value) -> bool: ...
    def _projection_count(self) -> int: ...

@final
class _syntax_Identity:
    def _same_identity(self, other: _syntax_Identity) -> bool: ...

def _syntax_construct(module_name: str, class_id: int, fields: tuple[object, ...]) -> _syntax_Value: ...
def _syntax_source_spans(
    value: _StrictTextSyntax | _RecoveredTextSyntax,
) -> tuple[_source_SourceSpan, ...]: ...
def _syntax_tree_eq_ignoring_spans(
    left: _StrictTextSyntax, right: _StrictTextSyntax
) -> bool: ...

@final
class _syntax_Token:
    __match_args__: ClassVar[tuple[str]]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, indicators: _SyntaxWithIndicators) -> _syntax_Token: ...
    @property
    def indicators(self) -> _SyntaxWithIndicators: ...
    @property
    def core_word(self) -> _MorphologyWordLike: ...
    @property
    def source_spans(self) -> tuple[_source_SourceSpan, ...]: ...
    def same_identity(self, other: _syntax_Token) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...

@final
class _syntax_PlainWithIndicators:
    __match_args__: ClassVar[tuple[str]]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, word_like: _MorphologyWordLike) -> _syntax_PlainWithIndicators: ...
    @property
    def word_like(self) -> _MorphologyWordLike: ...
    def same_identity(self, other: _SyntaxWithIndicators) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...

@final
class _syntax_EmphasizedWithIndicators:
    __match_args__: ClassVar[tuple[str, str, str]]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(
        cls,
        bahe: _MorphologyWord,
        extra_bahe: Sequence[_MorphologyWord],
        word_like: _MorphologyWordLike,
    ) -> _syntax_EmphasizedWithIndicators: ...
    @property
    def bahe(self) -> _MorphologyWord: ...
    @property
    def extra_bahe(self) -> tuple[_MorphologyWord, ...]: ...
    @property
    def word_like(self) -> _MorphologyWordLike: ...
    def same_identity(self, other: _SyntaxWithIndicators) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...

@final
class _syntax_IndicatorWithIndicators:
    __match_args__: ClassVar[tuple[str, str, str, str, str]]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(
        cls,
        base: _SyntaxWithIndicators,
        indicator_bahe: Sequence[_MorphologyWord],
        indicator: _MorphologyWord,
        nai_bahe: Sequence[_MorphologyWord],
        nai: _MorphologyWord | None,
    ) -> _syntax_IndicatorWithIndicators: ...
    @property
    def base(self) -> _SyntaxWithIndicators: ...
    @property
    def indicator_bahe(self) -> tuple[_MorphologyWord, ...]: ...
    @property
    def indicator(self) -> _MorphologyWord: ...
    @property
    def nai_bahe(self) -> tuple[_MorphologyWord, ...]: ...
    @property
    def nai(self) -> _MorphologyWord | None: ...
    def same_identity(self, other: _SyntaxWithIndicators) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...

_SyntaxWithIndicators = _syntax_PlainWithIndicators | _syntax_EmphasizedWithIndicators | _syntax_IndicatorWithIndicators

@final
class _syntax_SkippedTokens:
    __match_args__: ClassVar[tuple[str, str]]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, error_index: int, tokens: Sequence[_syntax_Token]) -> _syntax_SkippedTokens: ...
    @property
    def error_index(self) -> int: ...
    @property
    def tokens(self) -> tuple[_syntax_Token, ...]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...

@final
class _syntax_MissingRequiredField:
    __match_args__: ClassVar[tuple[str, str, str]]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(
        cls,
        error_index: int,
        span: _source_SourceSpan,
        expected: str,
    ) -> _syntax_MissingRequiredField: ...
    @property
    def error_index(self) -> int: ...
    @property
    def span(self) -> _source_SourceSpan: ...
    @property
    def expected(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
