[package]
name = "jbotci-semantics"
description = "Lojban semantic model and builder."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
exclude = ["/tests/**", "/benches/**", "/examples/**"]

[features]
expensive_contracts = []

[dependencies]
bityzba.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
jbotci-source.workspace = true
jbotci-dictionary.workspace = true
jbotci-jvozba.workspace = true
jbotci-morphology.workspace = true
jbotci-syntax.workspace = true
jbotci-tree.workspace = true
vec1.workspace = true

[build-dependencies]
bityzba = { workspace = true, features = ["contract_scanner"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
toml.workspace = true

[dev-dependencies]
jbotci-dictionary-data.workspace = true
jbotci-dialect.workspace = true
roxmltree.workspace = true
sha2.workspace = true
toml.workspace = true

[lints]
workspace = true
