[package]
name = "jbotci-cll"
description = "Reference data model for The Contemporary Lojban Language, jbotci's vendored Lojban reference grammar."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
expensive_contracts = []

[dependencies]
bityzba.workspace = true
bzip2.workspace = true
jbotci-morphology.workspace = true
roxmltree.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
jbotci-syntax.workspace = true
serde_json.workspace = true

[build-dependencies]
bityzba = { workspace = true, features = ["contract_scanner"] }
bzip2.workspace = true
serde.workspace = true
toml.workspace = true

[lints]
workspace = true
