[package]
name = "jbotci-tree"
description = "Generic ordered tree traversal utilities for jbotci model crates."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
exclude = ["/tests/**", "/ui/**", "/benches/**", "/examples/**"]

[features]
expensive_contracts = []

[dependencies]
bityzba.workspace = true
jbotci-source.workspace = true
jbotci-tree-macros.workspace = true
serde.workspace = true
smallvec.workspace = true
vec1.workspace = true

[dev-dependencies]
serde_json.workspace = true
trybuild = "1"

[build-dependencies]
bityzba = { workspace = true, features = ["contract_scanner"] }

[lints]
workspace = true
