# Generated by tools/compose_stubs.py; do not edit directly.
from typing import Final, final

__version__: Final[str]
__all__: tuple[str, ...]

class JbotciError(Exception):
    """Base exception for errors reported by jbotci."""

class InvalidInputError(JbotciError):
    """The supplied value is not valid input for an operation."""

def smoke() -> str:
    """Confirm that the native extension loaded and can execute Rust code."""

def raise_sample_error(message: str) -> None:
    """Raise a sample structured error through the shared conversion path."""

@final
class Sample:
    """Temporary immutable value object used to test binding conventions."""

    def __new__(cls, value: str) -> Sample: ...
    @property
    def value(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
