"""Declarative dialect formulas, feature sets, and settings."""

from typing import TypeAlias

from ._native import (
    _dialect_BuiltinDialect as BuiltinDialect,
    _dialect_CmavoExpansion as CmavoExpansion,
    _dialect_CmavoSwap as CmavoSwap,
    _dialect_CustomDialect as CustomDialect,
    _dialect_DialectDefinition as DialectDefinition,
    _dialect_DialectFeature as DialectFeature,
    _dialect_DialectSettings as DialectSettings,
    _dialect_add_dialect_formula_reference as add_dialect_formula_reference,
    _dialect_builtin_dialect_names as builtin_dialect_names,
    _dialect_builtin_dialects as builtin_dialects,
    _dialect_cmavo_dialect_entries_to_definition as cmavo_dialect_entries_to_definition,
    _dialect_custom_dialect_definition_to_johau_uri as custom_dialect_definition_to_johau_uri,
    _dialect_custom_dialect_definition_to_johau_uri_with_custom_dialects as custom_dialect_definition_to_johau_uri_with_custom_dialects,
    _dialect_custom_dialect_is_valid as custom_dialect_is_valid,
    _dialect_dialect_definition_to_johau_uri as dialect_definition_to_johau_uri,
    _dialect_dialect_definition_to_text as dialect_definition_to_text,
    _dialect_dialect_formula_top_level_references as dialect_formula_top_level_references,
    _dialect_dialect_name_shows_in_gentufa_picker as dialect_name_shows_in_gentufa_picker,
    _dialect_find_builtin_dialect as find_builtin_dialect,
    _dialect_import_johau_dialect_settings as import_johau_dialect_settings,
    _dialect_parse_dialect_definition as parse_dialect_definition,
    _dialect_parse_dialect_definition_with_custom_dialects as parse_dialect_definition_with_custom_dialects,
    _dialect_parse_dialect_selection_formula as parse_dialect_selection_formula,
    _dialect_parse_johau_dialect_uri as parse_johau_dialect_uri,
    _dialect_remove_dialect_formula_reference as remove_dialect_formula_reference,
    _dialect_replace_dialect_formula_reference as replace_dialect_formula_reference,
)

CmavoDialectEntry: TypeAlias = CmavoSwap | CmavoExpansion

__all__: tuple[str, ...] = (
    "DialectFeature",
    "CmavoSwap",
    "CmavoExpansion",
    "CmavoDialectEntry",
    "DialectDefinition",
    "BuiltinDialect",
    "CustomDialect",
    "DialectSettings",
    "parse_dialect_definition",
    "builtin_dialects",
    "builtin_dialect_names",
    "find_builtin_dialect",
    "parse_dialect_definition_with_custom_dialects",
    "parse_dialect_selection_formula",
    "custom_dialect_is_valid",
    "dialect_name_shows_in_gentufa_picker",
    "dialect_formula_top_level_references",
    "add_dialect_formula_reference",
    "remove_dialect_formula_reference",
    "replace_dialect_formula_reference",
    "dialect_definition_to_text",
    "cmavo_dialect_entries_to_definition",
    "custom_dialect_definition_to_johau_uri",
    "custom_dialect_definition_to_johau_uri_with_custom_dialects",
    "dialect_definition_to_johau_uri",
    "parse_johau_dialect_uri",
    "import_johau_dialect_settings",
)
