[package]
name = "xtask-common"
description = "Shared workspace automation support for jbotci."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[features]
expensive_contracts = []

[dependencies]
bityzba.workspace = true
jbotci-dialect.workspace = true
jbotci-diagnostics.workspace = true
jbotci-jvozba.workspace = true
jbotci-morphology.workspace = true
jbotci-orthography.workspace = true
jbotci-output.workspace = true
jbotci-source.workspace = true
jbotci-syntax.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_stacker.workspace = true
thiserror.workspace = true
toml.workspace = true
toml_edit.workspace = true
walkdir.workspace = true

[build-dependencies]
bityzba = { workspace = true, features = ["contract_scanner"] }

[lints]
workspace = true
