"""Tests for the artifact tool that normalizes Maturin's raw sdist.

These exercise `tools.python_artifacts` directly against synthetic archives, so
they need neither the installed package nor a real Maturin run.
"""

from __future__ import annotations

import gzip
import io
import shutil
import subprocess
import tarfile
from pathlib import Path

import pytest

from tools.python_artifacts import (
    SDIST_OMITTED_PATCH,
    SDIST_OMITTED_WORKSPACE_DEPENDENCIES,
    normalize_sdist,
)

ARCHIVE_ROOT = "jbotci-artifact-tool-0.0.0"

# A lockfile that does not describe the packaged workspace, exactly as Maturin
# ships this repository's lockfile for a workspace it has just pruned: the
# `dependency` package and `member`'s edge to it are both missing.
STALE_WORKSPACE_LOCK = b"""\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "member"
version = "0.0.0"
"""

MEMBER_MANIFEST = b"""\
[package]
name = "member"
version = "0.0.0"
edition = "2021"

[dependencies]
dependency = { path = "../dependency" }
"""

DEPENDENCY_MANIFEST = b"""\
[package]
name = "dependency"
version = "0.0.0"
edition = "2021"
"""


def workspace_manifest(members: str) -> bytes:
    """Build a root manifest carrying every reference normalization removes."""
    return (
        b"[workspace]\n"
        + f"members = [{members}]\n".encode()
        + b'resolver = "3"\n'
        + b"\n"
        + b"[workspace.dependencies]\n"
        + b"".join(SDIST_OMITTED_WORKSPACE_DEPENDENCIES)
        + b"\n"
        + SDIST_OMITTED_PATCH
    )


def write_sdist(path: Path, members: dict[str, bytes]) -> None:
    """Write a minimal single-root source distribution."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with (
        path.open("wb") as raw,
        gzip.GzipFile(
            filename="", mode="wb", fileobj=raw, mtime=0
        ) as compressed,
        tarfile.open(
            fileobj=compressed, mode="w", format=tarfile.PAX_FORMAT
        ) as archive,
    ):
        for name, contents in members.items():
            entry = tarfile.TarInfo(f"{ARCHIVE_ROOT}/{name}")
            entry.size = len(contents)
            entry.mode = 0o644
            archive.addfile(entry, io.BytesIO(contents))


def packaged_workspace(
    members: str = '"member", "dependency"',
) -> dict[str, bytes]:
    """Return the members of a synthetic raw source distribution."""
    return {
        "Cargo.toml": workspace_manifest(members),
        "Cargo.lock": STALE_WORKSPACE_LOCK,
        "member/Cargo.toml": MEMBER_MANIFEST,
        "member/src/lib.rs": b"",
        "dependency/Cargo.toml": DEPENDENCY_MANIFEST,
        "dependency/src/lib.rs": b"",
    }


def normalized_workspace(tmp_path: Path, members: dict[str, bytes]) -> Path:
    """Normalize a synthetic distribution and return its extracted root."""
    raw = tmp_path / "raw" / f"{ARCHIVE_ROOT}.tar.gz"
    write_sdist(raw, members)
    normalized = tmp_path / "normalized" / f"{ARCHIVE_ROOT}.tar.gz"
    normalize_sdist(raw, normalized)

    extracted = tmp_path / "extracted"
    with tarfile.open(normalized, "r:gz") as archive:
        archive.extractall(extracted, filter="data")
    return extracted / ARCHIVE_ROOT


def canonical_lockfile(workspace: Path, scratch: Path) -> bytes:
    """Return the lockfile cargo writes for `workspace` from nothing."""
    shutil.copytree(workspace, scratch)
    (scratch / "Cargo.lock").unlink()
    subprocess.run(
        [
            "cargo",
            "metadata",
            "--manifest-path",
            str(scratch / "Cargo.toml"),
            "--format-version",
            "1",
            "--offline",
        ],
        stdout=subprocess.DEVNULL,
        check=True,
    )
    return (scratch / "Cargo.lock").read_bytes()


def test_normalization_writes_the_canonical_packaged_lockfile(
    tmp_path: Path,
) -> None:
    """Leave the lockfile cargo itself writes for the packaged workspace.

    A source distribution is a pruned workspace, and Maturin ships the
    repository lockfile rather than one for that smaller workspace. Consumers
    build the archive with `cargo fetch --locked` and `maturin build --locked`,
    which refuse to update a lockfile, so normalization has to resolve the
    packaged workspace and write the canonical result.
    """
    root = normalized_workspace(tmp_path, packaged_workspace())

    manifest = (root / "Cargo.toml").read_bytes()
    assert SDIST_OMITTED_PATCH not in manifest
    for dependency in SDIST_OMITTED_WORKSPACE_DEPENDENCIES:
        assert dependency not in manifest

    lockfile = (root / "Cargo.lock").read_bytes()
    assert lockfile != STALE_WORKSPACE_LOCK
    assert lockfile == canonical_lockfile(root, tmp_path / "canonical")
    subprocess.run(
        [
            "cargo",
            "fetch",
            "--locked",
            "--manifest-path",
            str(root / "Cargo.toml"),
        ],
        stdout=subprocess.DEVNULL,
        check=True,
    )


def test_normalization_fails_closed_on_an_unloadable_workspace(
    tmp_path: Path,
) -> None:
    """Reject a packaged workspace whose members are not all in the archive."""
    with pytest.raises(subprocess.CalledProcessError):
        normalized_workspace(
            tmp_path, packaged_workspace('"member", "dependency", "absent"')
        )
    assert not (tmp_path / "normalized" / f"{ARCHIVE_ROOT}.tar.gz").exists()
